# Generated by Django 3.0.2 on 2020-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
