# Generated by Django 3.0.2 on 2020-02-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('articles', '0003_auto_20200201_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='photos.Photo'),
        ),
    ]
